import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
import { api } from "../../../../convex/_generated/api";
import { Id } from "../../../../convex/_generated/dataModel";
import { generateWorkflowCode } from "@/lib/codegen";
import { Octokit } from "octokit";

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

interface DeployRequestBody {
  workflowId: string;
  workspaceId: string;
  githubRepo: string;
  githubBranch?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: DeployRequestBody = await request.json();
    const { workflowId, workspaceId, githubRepo, githubBranch = "main" } = body;

    if (!workflowId || !workspaceId || !githubRepo) {
      return NextResponse.json(
        { error: "Missing required fields: workflowId, workspaceId, githubRepo" },
        { status: 400 }
      );
    }

    // Get the workflow
    const workflow = await convex.query(api.workflows.get, {
      id: workflowId as Id<"workflows">,
    });

    if (!workflow) {
      return NextResponse.json({ error: "Workflow not found" }, { status: 404 });
    }

    // Get GitHub connection for this workspace
    const githubConnection = await convex.query(api.connections.getAccessToken, {
      workspaceId: workspaceId as Id<"workspaces">,
      provider: "github",
    });

    if (!githubConnection?.accessToken) {
      return NextResponse.json(
        { error: "GitHub not connected. Please connect GitHub first." },
        { status: 400 }
      );
    }

    // Create deployment record
    const deploymentId = await convex.mutation(api.deployments.create, {
      workflowId: workflowId as Id<"workflows">,
      workspaceId: workspaceId as Id<"workspaces">,
      version: workflow.version,
      githubRepo,
      githubBranch,
    });

    // Update status to deploying
    await convex.mutation(api.deployments.updateStatus, {
      id: deploymentId,
      status: "deploying",
    });

    try {
      // Generate the code
      const generatedCode = generateWorkflowCode({
        _id: workflow._id,
        name: workflow.name,
        description: workflow.description,
        nodes: workflow.nodes,
        edges: workflow.edges,
        version: workflow.version,
      });

      // Store generated code
      await convex.mutation(api.deployments.updateGeneratedCode, {
        id: deploymentId,
        generatedCode: JSON.stringify(generatedCode, null, 2),
      });

      // Push to GitHub
      const octokit = new Octokit({ auth: githubConnection.accessToken });
      const [owner, repo] = githubRepo.split("/");

      if (!owner || !repo) {
        throw new Error("Invalid GitHub repo format. Expected: owner/repo");
      }

      // Get current commit SHA for the branch
      let baseSha: string;
      try {
        const { data: refData } = await octokit.rest.git.getRef({
          owner,
          repo,
          ref: `heads/${githubBranch}`,
        });
        baseSha = refData.object.sha;
      } catch {
        // Branch doesn't exist, get default branch
        const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
        const { data: defaultRef } = await octokit.rest.git.getRef({
          owner,
          repo,
          ref: `heads/${repoData.default_branch}`,
        });
        baseSha = defaultRef.object.sha;
      }

      // Create blobs for each file
      const blobs = await Promise.all(
        generatedCode.files.map(async (file) => {
          const { data: blob } = await octokit.rest.git.createBlob({
            owner,
            repo,
            content: Buffer.from(file.content).toString("base64"),
            encoding: "base64",
          });
          return {
            path: file.path,
            mode: "100644" as const,
            type: "blob" as const,
            sha: blob.sha,
          };
        })
      );

      // Get current tree
      const { data: baseCommit } = await octokit.rest.git.getCommit({
        owner,
        repo,
        commit_sha: baseSha,
      });

      // Create new tree
      const { data: newTree } = await octokit.rest.git.createTree({
        owner,
        repo,
        base_tree: baseCommit.tree.sha,
        tree: blobs,
      });

      // Create commit
      const { data: newCommit } = await octokit.rest.git.createCommit({
        owner,
        repo,
        message: `Deploy workflow: ${workflow.name} (v${workflow.version})\n\nGenerated by Orchest`,
        tree: newTree.sha,
        parents: [baseSha],
      });

      // Update branch reference
      try {
        await octokit.rest.git.updateRef({
          owner,
          repo,
          ref: `heads/${githubBranch}`,
          sha: newCommit.sha,
        });
      } catch {
        // Branch doesn't exist, create it
        await octokit.rest.git.createRef({
          owner,
          repo,
          ref: `refs/heads/${githubBranch}`,
          sha: newCommit.sha,
        });
      }

      // Update deployment as successful
      await convex.mutation(api.deployments.updateStatus, {
        id: deploymentId,
        status: "deployed",
        commitSha: newCommit.sha,
        deployUrl: `https://github.com/${githubRepo}/tree/${githubBranch}`,
      });

      return NextResponse.json({
        success: true,
        deploymentId,
        commitSha: newCommit.sha,
        deployUrl: `https://github.com/${githubRepo}/tree/${githubBranch}`,
        filesDeployed: generatedCode.files.map((f) => f.path),
      });
    } catch (error) {
      // Update deployment as failed
      const errorMessage = error instanceof Error ? error.message : "Deployment failed";
      await convex.mutation(api.deployments.updateStatus, {
        id: deploymentId,
        status: "failed",
        error: errorMessage,
      });

      return NextResponse.json(
        { error: errorMessage, deploymentId },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error("Deploy error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal server error" },
      { status: 500 }
    );
  }
}
